[package]
name = "ic-bn-lib"

edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

description = "Internet Computer Boundary Nodes shared modules"
# Version is set by a Github workflow from the git tag
version = "0.0.0-git"
documentation = "https://docs.rs/ic-bn-lib"

[features]
default = []

acme = [
    "dep:instant-acme",
    "dep:rcgen",
    "dep:hyper-rustls",
    "dep:tar",
    "dep:flate2",
    "dep:hex",
    "dep:sha2",
]
acme-dns = ["acme"]
acme-alpn = ["acme", "dep:rustls-acme"]
clients-hyper = ["dep:hyper-rustls"]
custom-domains = ["acme-dns"]
custom-domains-openapi = ["custom-domains", "dep:utoipa", "dep:utoipa-swagger-ui"]
cert-providers = ["custom-domains"]
lb = []
pubsub = []
sev-snp = ["dep:sev"]
smtp = ["custom-domains", "dep:mail-auth", "dep:mail-parser", "dep:smtp-proto"]
vector = ["dep:vrl", "dep:prost", "dep:prost-types"]

[dependencies]
ahash = { workspace = true }
anyhow = { workspace = true }
arc-swap = { workspace = true }
arrayvec = { workspace = true }
async-channel = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
candid = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
chacha20poly1305 = { workspace = true }
derive-new = { workspace = true }
flate2 = { workspace = true, optional = true }
fqdn = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
governor = { workspace = true }
hex = { workspace = true, optional = true }
hickory-proto = { workspace = true }
hickory-resolver = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
humantime = { workspace = true }
hyper = { workspace = true }
hyper-rustls = { workspace = true, optional = true }
hyper-util = { workspace = true }
ic-agent = { workspace = true }
ic-custom-domains-canister-api = { workspace = true }
indoc = { workspace = true }
instant-acme = { workspace = true, optional = true }
itertools = { workspace = true }
mail-auth = { workspace = true, optional = true }
mail-parser = { workspace = true, optional = true }
moka = { workspace = true }
nix = { workspace = true }
parse-size = { workspace = true }
ppp = { workspace = true }
pem = { workspace = true }
prometheus = { workspace = true }
prost = { workspace = true, optional = true }
prost-types = { workspace = true, optional = true }
rand = { workspace = true }
rcgen = { workspace = true, optional = true }
regex = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
rustls-acme = { workspace = true, optional = true }
rustls-pemfile = { workspace = true }
rustls-platform-verifier = { workspace = true }
scopeguard = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
serde_yaml_ng = { workspace = true }
sev = { workspace = true, optional = true }
sha1 = { workspace = true }
sha2 = { workspace = true, optional = true }
show-option = { workspace = true }
smtp-proto = { workspace = true, optional = true }
socket2 = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
systemstat = { workspace = true }
tar = { workspace = true, optional = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-rustls = { workspace = true }
tokio-io-timeout = { workspace = true }
tower = { workspace = true }
tower_governor = { workspace = true }
tower-service = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
utoipa = { workspace = true, optional = true }
utoipa-swagger-ui = { workspace = true, optional = true }
uuid = { workspace = true }
vrl = { workspace = true, optional = true }
webpki-root-certs = { workspace = true }
x509-parser = { workspace = true }
zeroize = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
axum-server = { workspace = true }
criterion = { workspace = true }
mail-send = { workspace = true }
mockall = { workspace = true }
mock-io = { workspace = true }
pocket-ic = { workspace = true }
rand_regex = { workspace = true }
tempfile = { workspace = true }
tokio-test = { workspace = true }

[[bench]]
name = "vector"
harness = false
required-features = ["vector"]

[package.metadata.cargo-all-features]
# Limit feature combinations to reduce test duration
max_combination_size = 2

[[bin]]
name = "cloudflare-test"
path = "tools/cloudflare-test.rs"
required-features = ["acme-dns"]
